### ISSUE TITLE
pathDIP data

### ISSUE THREAD

**Issue by hxy265** [hui2000ji/scETM#5]
Hi, really nice package!
I am trying to run this with pathDIP data but when i use the download link https://ophid.utoronto.ca/pathDIP/Download.jsp I get files such as CURATE_V4.txt. This appears to be different to pathway_gene_matv4.csv in the vignette. How do i generate this csv from the downloaded files? Thanks!

**Comment by yifnzhao** [comment]
Hello! Thanks for your interest in scETM. The pathway-gene matrix simply needs to be a binary matrix -- entry (i,j) equals 1 if pathway i includes gene j according to a user-defined pathway database, such as pathDIP; entry (i,j) equals 0 otherwise. Please don't hesitate to follow up if anything's unclear!

Yifan

**Comment by hxy265** [comment]
Thanks, is there any chance you can provide this as a reference file? It would make is a lot easier!

**Comment by yifnzhao** [comment]
Given that data access to pathDIP is regulated by [Jurisica Lab](https://ophid.utoronto.ca/pathDIP/Researchers.jsp), currently I don't think we have plans (or the right permission) to release this dataset in our repository. As I described above, once you download the data, it is very simple to convert it to a pathway-gene binary matrix. 

Yifan
